print("First 10 letters in lower case:")
a = head(letters, 10)
print(a)
print("Last 10 letters in upper case:")
b = tail(LETTERS, 10)
print(b)
print("Letters between 22nd to 24th letters in upper case:")
c = tail(LETTERS[22:24])
print(c)